# Generated by Django 5.2.7 on 2026-02-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stuid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('stuname', models.CharField(max_length=20)),
                ('stusex', models.CharField(max_length=10)),
                ('stubirth', models.DateField()),
            ],
        ),
    ]
