# Generated by Django 6.0.3 on 2026-06-14 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
