# Generated by Django 5.2.7 on 2026-02-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.IntegerField(max_length=15)),
                ('address', models.CharField()),
                ('intrest', models.CharField()),
            ],
        ),
    ]
